name = "RL_TSP"
uuid = "8c343498-0108-4684-8a59-2e9c4f8b1d08"
authors = ["Taki Eddine HARBI <38916249+takiedinne@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
